### ISSUE TITLE
Numpy 1.19 SX|MX object has no attribute 'full'

### ISSUE THREAD

**Issue by tmmsartor** [casadi/casadi#2625]
How to replicate:

Install `casadi` and `numpy>=1.19`

```
from casadi import MX
from numpy import cos
x = MX.sym("x")
y = cos(x) 
```
Also SX is affected

Error message:
```
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/issue_2624/lib/python3.7/site-packages/casadi/casadi.py", line 10824, in __array__
    return self.full()
  File "/home/user/.pyenv/versions/issue_2624/lib/python3.7/site-packages/casadi/casadi.py", line 9485, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, MX, name)
  File "/home/user/.pyenv/versions/issue_2624/lib/python3.7/site-packages/casadi/casadi.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'MX' object has no attribute 'full'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    y = cos(x)
  File "/home/user/.pyenv/versions/issue_2624/lib/python3.7/site-packages/casadi/casadi.py", line 10828, in __array__
    + "Use an equivalent CasADi function instead of that numpy function.")
Exception: Implicit conversion of symbolic CasADi type to numeric matrix not supported.
This may occur when you pass a CasADi object to a numpy function.
Use an equivalent CasADi function instead of that numpy function.
```

**Comment by jgillis** [comment]
Probably caused by https://github.com/numpy/numpy/pull/15118 because of https://github.com/casadi/casadi/blob/3.5.1/swig/casadi.i#L2603-L2643

**Comment by mattip** [comment]
How did that used to work? What provided the `context` argument?

**Comment by jgillis** [comment]
I think it corresponded a tuple containing `ufunc` and `inputs` arguments of `__array_ufunc__(self, ufunc, method, *inputs, **kwargs)`, which I didn't know about until today.

**Comment by mattip** [comment]
The line you point to above is using `__array_wrap__` which should not have changed. Only `__array__` was meant to have changed. Did I mess up somewhere?

**Comment by jgillis** [comment]
There is a convoluted check for existance of context argument also in the '__array__' method directly below.
I guess ufunc itself passed that argument?
Anyhow, __array_ufunc__ seems superior

**Comment by eric-wieser** [comment]
Those lines pointer to are _both_ `__array__` and `__array_wrap__`/

**Comment by eric-wieser** [comment]
My guess is that the `else` path was just never exercised before, and the code there never worked.

**Comment by jgillis** [comment]
### For CasADi users using CasADi 3.5.1 or earlier

You may fix this issue by installing `casadi_hotfixes` with `pip`, and then inserting `import casadi_hotfixes` once (no harm is done if you do it multiple times) before or after your regular `import casadi` or `from casadi import *`
