### ISSUE TITLE
External function derivative detection in CasADi 3.6.x

### ISSUE THREAD

**Issue by PeterMeisrimelModelon** [casadi/casadi#3593]
Hi,

we are currently trying to upgrade from 3.5.5 to 3.6.4 and are having some issues.
Setup we are using (works fine with v3.5.5):

- Utilizing external C functions, possibly with generated derivatives; not utilizing any sparsity information.
- Use external functions in NLP (constraints, costs)
- load external functions with `opts["enable_fd"] = true`, such that finite differences are used in the absence of generated derivate functions

We are getting the following error stack trace in a cases with an external function `EXTERNAL_FUNCTION` and a generated derivate `fwd1_EXTERNAL_FUNCTION`:

```
.../casadi/core/function_internal.cpp:146: Error calling IpoptInterface::init for 'solver':
Error in Function::factory for 'nlp' [MXFunction] at .../casadi/core/function.cpp:1758:
Failed to create nlp_hess_l:[x, p, lam:f, lam:g]->[triu:hess:gamma:x:x] with {"gamma": [f, g]}:
.../casadi/core/factory.hpp:591: Hessian generation failed:
.../casadi/core/factory.hpp:512: Calculating Hessian of gamma w.r.t. [x] and [x]: Error in MX::hessian at .../casadi/core/mx.cpp:1724:
Error in MX::jacobian at .../casadi/core/mx.cpp:1708:
Error in XFunction::jac for 'helper_jacobian_MX' [MXFunction] at .../casadi/core/x_function.hpp:804:
Error in MXFunction::ad_forward at .../casadi/core/mx_function.cpp:890:
Error in MX::ad_forward for node of type N6casadi4CallE at .../casadi/core/mx.cpp:2301:
Error in Call::ad_forward for 'adj1_dae_l0_fcn' [MXFunction] at .../casadi/core/casadi_call.cpp:121:
Error in Function::forward for 'adj1_dae_l0_fcn' [MXFunction] at .../casadi/core/function.cpp:1083:
Error in XFunction::get_forward for 'adj1_dae_l0_fcn' [MXFunction] at .../casadi/core/x_function.hpp:856:
Error in MXFunction::ad_forward at .../casadi/core/mx_function.cpp:890:
Error in MX::ad_forward for node of type N6casadi4CallE at .../casadi/core/mx.cpp:2301:
Error in Call::ad_forward for 'jac_wrap_EXTERNAL_FUNCTION' [MXFunction] at .../casadi/core/casadi_call.cpp:121:
Error in Function::forward for 'jac_wrap_EXTERNAL_FUNCTION' [MXFunction] at .../casadi/core/function.cpp:1083:
Error in XFunction::get_forward for 'jac_wrap_EXTERNAL_FUNCTION' [MXFunction] at .../casadi/core/x_function.hpp:856:
Error in MXFunction::ad_forward at .../casadi/core/mx_function.cpp:890:
Error in MX::ad_forward for node of type N6casadi4CallE at .../casadi/core/mx.cpp:2301:
Error in Call::ad_forward for 'fwd1_EXTERNAL_FUNCTION' [External] at .../casadi/core/casadi_call.cpp:121:
.../casadi/core/function_internal.cpp:2879: Assertion "has_derivative()" failed:
Derivatives cannot be calculated for fwd1_EXTERNAL_FUNCTION
```

From what we can tell, CasADi is going through various possible options for computing the hessian, but ultimately fails to find any, despite the fact that finite differences should be used. If we additionally set `opts["enable_forward"] = false`, the above error will no longer be generated, but CasADi will no longer use generated external derivates.

There are a couple of notes in the changelog that are possibly related, but none very obviously. 

Any help/pointers would be appreciated.

**Comment by modelonrobinandersson** [comment]
Hi @jaeandersson thank you for your quick reply. Do you have any suggestions for how we could debug this further? Especially since this was working with CasADi 3.5.5. Is there anything you are aware of from the previous version that:
1. changes how the derivative function is generated, or
2. changes how the differentiation is done?

**Comment by jaeandersson** [comment]
Not off the top of my head. You could look exactly at what kind of derivative functions were generated in 3.5.5 to figure out when it starts diverging from 3.6. Once you've figured out why it's behaving different, you can think of a way to resolve the issue. In any case, second derivatives using FD only is not really recommended, so I'm not even so sure it really worked for you in 3.5.5 either.

**Comment by PeterMeisrimelModelon** [comment]
Thanks for the input, maybe some clarifications:

1. Both `EXTERNAL_FUNCTION `and `fwd1_EXTERNAL_FUNCTION` are external functions, `fwd1_EXTERNAL_FUNCTION` is **not** generated via forward AD.
2. The expected behavior here is that by explicitly setting `opts["enable_fd"] = true`, the second derivative will be calculated using finite differences on `fwd1_EXTERNAL_FUNCTION`. We are aware that finite differences are not really the best option, but due to the nature of the external functions, it is the only option.
3. We could not find any changes in the ReleaseNotes resp. diffs since 3.5.5 with respect to `enable_fd`, yet the assert implies that the explicit `opts["enable_fd"] = true` has been discarded. The offending assert not being a new addition either.
4. Also for completeness, the error is generated when (trying) to create the NLP solver.

/Peter

**Comment by modelonrobinandersson** [comment]
Hi @jaeandersson. After some additional debugging we believe the error we are observing is due to the changes in https://github.com/casadi/casadi/issues/2848, among them I see that some options (in particular `enable_fd`) are no longer propagated due to the added if-statement (https://github.com/casadi/casadi/commit/6b7dc1d03f4828e6b3f21b7ad03e472ef83c6601#diff-3f30bada163de7ee828d1f3dd0fe431e8233b97aef17d841b8498f1df2507415R385).

Could you comment on the following:
1. Is it intentional to no longer propagate `enable_fd`?
2. If yes, do you have any proposal for what we can change such that the second derivative gets calculated using fd?

**Comment by jaeandersson** [comment]
> 1. Is it intentional to no longer propagate `enable_fd`?

Yes, it's intentional. In your case, you don't want to enable FD for the function itself, but for its derivative.

> 2. If yes, do you have any proposal for what we can change such that the second derivative gets calculated using fd?

You should be able to pass `enable_fd` to to the first order derivative function directly. Try to set 
```python
opts["forward_options"] = dict(enable_fd = True)
```

**Comment by PeterMeisrimelModelon** [comment]
> > 1. Is it intentional to no longer propagate `enable_fd`?
> 
> Yes, it's intentional. In your case, you don't want to enable FD for the function itself, but for its derivative.
> 
> > 2. If yes, do you have any proposal for what we can change such that the second derivative gets calculated using fd?
> 
> You should be able to pass `enable_fd` to to the first order derivative function directly. Try to set
> 
> ```python
> opts["forward_options"] = dict(enable_fd = True)
> ```

We could resolve the issue on our side by additionally adding enable_fd as explicit forward option as you suggested.

Thanks for the help!
