### ISSUE TITLE
undefined reference to `casadi::difference` when building in windows/mingw

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#3723]
```
[build] C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\_casadi.dir/objects.a(casadiPYTHON_wrap.cxx.obj): in function `_wrap_difference':
[build] C:/Projects/gm/fmiopt/casadi/out/build/windevel/swig/casadiPYTHON_wrap.cxx:36145:(.text+0x6b8b1): undefined reference to `casadi::difference(std::vector<casadi::MX, std::allocator<casadi::MX> > const&, std::vector<casadi::MX, std::allocator<casadi::MX> > const&)'
```

Appears to be caused by https://github.com/casadi/casadi/commit/a6cb72652caff0c4787dffa0ee96421e91d061f0

**Comment by jaeandersson** [comment]
MX::difference doesn't use the right pattern. Should be a static function and an inline friend function pair, like the other functions in the class
