### ISSUE TITLE
Callback function to define manually jacobians does not work with CasADi 3.5.5

### ISSUE THREAD

**Issue by gianluigigrandesso** [casadi/casadi#3217]
Hi!
I'm having some troubles with the Callback functionality of CasADi. What I'm trying to do is to use an external function (through the Callback functionality) for a constraint in an nlp to be solved with Ipopt. If I use finite differences (option "enable_fd": True) then everything works.
The problem arises when I try to pass the jacobian to avoid the use of finite differences. I get the following error:

> Traceback (most recent call last):
  File "/test_issue_github.py", line 67, in <module>
    solver = nlpsol('solver',"ipopt",nlp)
  File "/opt/openrobots/lib/python3.6/site-packages/casadi/casadi.py", line 11059, in nlpsol
    return _casadi.nlpsol(*args)
RuntimeError: .../casadi/core/function_internal.cpp:145: Error calling IpoptInterface::init for 'solver':
Error in Function::factory for 'nlp' [MXFunction] at .../casadi/core/function.cpp:1634:
Failed to create nlp_grad:[x, p, lam:f, lam:g]->[f, g, grad:gamma:x, grad:gamma:p] with {"gamma": [f, g]}:
.../casadi/core/factory.hpp:367: Gradient generation failed:
Error in MX::gradient at .../casadi/core/generic_matrix.hpp:1203:
Error in MX::jtimes at .../casadi/core/generic_matrix.hpp:1191:
Error in MX::reverse at .../casadi/core/mx.cpp:1741:
Error in MXFunction::ad_reverse at .../casadi/core/mx_function.cpp:1042:
Error in MX::ad_reverse for node of type N6casadi4CallE at .../casadi/core/mx.cpp:2044:
Error in Call::ad_reverse for 'my_sin' [CallbackInternal] at .../casadi/core/casadi_call.cpp:147:
.../casadi/core/function_internal.cpp:2096: Assertion "ret.n_in()==n_in_ + n_out_" failed:
Notify the CasADi developers.

Here is a minimal example to replicate the error (based on option 4 in https://github.com/casadi/casadi/blob/main/docs/examples/python/callback.py):

```python
from casadi import *

class test_fun(Callback):
    def __init__(self, name, opts = {}):
        Callback.__init__(self)
        self.construct(name, opts)

    def get_n_in(self):  return 2
    def get_n_out(self): return 1

    def get_sparsity_in(self,n_in):
        if n_in == 0: return Sparsity.dense(2,1)
        if n_in == 1: return Sparsity.dense(1,1)

    def get_sparsity_out(self,n_out): return Sparsity.dense(1,1)

    def eval(self, arg):
        x = arg[0]
        p = arg[1]
        f = sin(x[0]+p)
        return [f]

    def has_jacobian(self): return True

    def get_jacobian(self,name,inames,onames,opts):
        f = test_jac_fun(name)
        x = MX.sym("x",2,1) 
        p = MX.sym('p',1,1)
        J = Function('jacobian',[x,p],[horzcat(jacobian(f(x,p),x),jacobian(f(x,p),p))])
        return J

class test_jac_fun(test_fun):
  def has_jacobian(self): return True
  def get_jacobian(self,name,inames,onames,opts):
    class JacFun(Callback):
        def __init__(self, opts={}):
            Callback.__init__(self)
            self.construct(name, opts)
            
        def get_n_in(self):  return 3
        def get_n_out(self): return 1
        
        def get_sparsity_in(self,n_in):
            if n_in == 0: return Sparsity.dense(2,1)    # first nominal output
            elif n_in == 1: return Sparsity.dense(1,1)  # second nominal input
            elif n_in == 2: return Sparsity(1,1)        # nominal output
            
        def get_sparsity_out(self,n_out):
            return Sparsity.dense(1,3)

        def eval(self, arg):
            x = arg[0]
            p = arg[1]
            jac = horzcat(cos(x[0]+p),0,0)
            return [jac]
    
    self.jac_callback = JacFun()
    return self.jac_callback

my_sin = test_fun('my_sin')

x = MX.sym('x',2,1)
p = MX.sym('p',1,1)

nlp = {'x':x,'p':p,'f':-my_sin(x,p),'g':x[1]}

solver = nlpsol('solver',"ipopt",nlp)

pnum = 0.5

arg = {}
arg['lbx'] = 0
arg['ubx'] = 3.14

arg['lbg'] = 1
arg['ubg'] = 1

arg['p'] = pnum

sol = solver(**arg)
```

Does anybody have an idea how to solve this issue?
Thank you!

GG

**Comment by jgillis** [comment]
You need to specify extra inputs with the shape of the outputs. You may use a dummy MX.sym for this if your jacobian computation cannot benefit from knowledge of the nominal outputs passed through these extra inputs..

**Comment by gianluigigrandesso** [comment]
Thank you @jgillis for your help, your advice fixed that issue.
Unfortunately, I get another error now:

> File "test_issue_github.py", line 70, in <module>
    solver = nlpsol('solver',"ipopt",nlp,options)
  File "/opt/openrobots/lib/python3.6/site-packages/casadi/casadi.py", line 11059, in nlpsol
    return _casadi.nlpsol(*args)
RuntimeError: .../casadi/core/function_internal.cpp:145: Error calling IpoptInterface::init for 'solver':
Error in Function::factory for 'nlp' [MXFunction] at .../casadi/core/function.cpp:1634:
Failed to create nlp_hess_l:[x, p, lam:f, lam:g]->[hess:gamma: x:x] with {"gamma": [f, g]}:
.../casadi/core/factory.hpp:387: Hessian generation failed:
Error in MX::hessian at .../casadi/core/mx.cpp:1679:
Error in MX::jacobian at .../casadi/core/mx.cpp:1663:
Error in XFunction::jac for 'helper_jacobian_MX' [MXFunction] at .../casadi/core/x_function.hpp:719:
Error in MXFunction::ad_forward at .../casadi/core/mx_function.cpp:831:
Error in MX::ad_forward for node of type N6casadi4CallE at .../casadi/core/mx.cpp:2035:
Error in Call::ad_forward for 'jacobian' [MXFunction] at .../casadi/core/casadi_call.cpp:123:
Error in Function::forward for 'jacobian' [MXFunction] at .../casadi/core/function.cpp:1017:
Error in XFunction::get_forward for 'jacobian' [MXFunction] at .../casadi/core/x_function.hpp:766:
Error in MXFunction::ad_forward at .../casadi/core/mx_function.cpp:831:
Error in MX::ad_forward for node of type N6casadi4CallE at .../casadi/core/mx.cpp:2035:
Error in Call::ad_forward for 'jac_jac_my_sin' [CallbackInternal] at .../casadi/core/casadi_call.cpp:123:
.../casadi/core/function_internal.cpp:2639: Assertion "has_derivative()" failed:
Derivatives cannot be calculated for jac_jac_my_sin

Which makes sense since I'm not providing Ipopt with the second derivative. So I pass the option "ipopt.hessian_approximation" : "limited-memory" to Ipopt to make it approximate the hessian of the lagrangian. But I get the following error:

> This is Ipopt version 3.11.9, running with linear solver mumps.
> NOTE: Other linear solvers might be more efficient (see Ipopt documentation).
> 
> Number of nonzeros in equality constraint Jacobian...:        1
> Number of nonzeros in inequality constraint Jacobian.:        0
> Number of nonzeros in Lagrangian Hessian.............:        0
> 
> CasADi - 2023-06-05 15:02:48 WARNING("solver:nlp_grad_f failed:Error in Function::operator() for 'nlp_grad_f' [MXFunction] at .../casadi/core/function.cpp:1368:
> Error in Function::operator() for 'jacobian' [MXFunction] at .../casadi/core/function.cpp:1368:
> Error in Function::operator() for 'jac_jac_my_sin' [CallbackInternal] at .../casadi/core/function.cpp:1368:
> .../casadi/core/function_internal.cpp:3366: Failed to evaluate 'eval_dm' for jac_jac_my_sin:
> .../casadi/core/callback_internal.cpp:122: Error calling "eval" for object jac_jac_my_sin:
> .../casadi/core/callback_internal.cpp:122: Assertion "(self_)!=0" failed:
> Callback object has been deleted") [.../casadi/core/oracle_function.cpp:223]
> Error evaluating objective gradient at user provided starting point.
>   No scaling factor for objective function computed!
> CasADi - 2023-06-05 15:02:48 WARNING("solver:nlp_grad_f failed:Error in Function::operator() for 'nlp_grad_f' [MXFunction] at .../casadi/core/function.cpp:1368:
> Error in Function::operator() for 'jacobian' [MXFunction] at .../casadi/core/function.cpp:1368:
> Error in Function::operator() for 'jac_jac_my_sin' [CallbackInternal] at .../casadi/core/function.cpp:1368:
> .../casadi/core/function_internal.cpp:3366: Failed to evaluate 'eval_dm' for jac_jac_my_sin:
> .../casadi/core/callback_internal.cpp:122: Error calling "eval" for object jac_jac_my_sin:
> .../casadi/core/callback_internal.cpp:122: Assertion "(self_)!=0" failed:
> Callback object has been deleted") [.../casadi/core/oracle_function.cpp:223]
> 
> Number of Iterations....: 0
> 
> Number of objective function evaluations             = 0
> Number of objective gradient evaluations             = 1
> Number of equality constraint evaluations            = 0
> Number of inequality constraint evaluations          = 0
> Number of equality constraint Jacobian evaluations   = 1
> Number of inequality constraint Jacobian evaluations = 0
> Number of Lagrangian Hessian evaluations             = 0
> Total CPU secs in IPOPT (w/o function evaluations)   =      0.000
> Total CPU secs in NLP function evaluations           =      0.000
> 
> EXIT: Invalid number in NLP function or derivative detected.
> CasADi - 2023-06-05 15:02:48 WARNING("solver:nlp_grad failed:Error in Function::operator() for 'nlp_grad' [MXFunction] at .../casadi/core/function.cpp:1368:
> Error in Function::operator() for 'jacobian' [MXFunction] at .../casadi/core/function.cpp:1368:
> Error in Function::operator() for 'jac_jac_my_sin' [CallbackInternal] at .../casadi/core/function.cpp:1368:
> .../casadi/core/function_internal.cpp:3366: Failed to evaluate 'eval_dm' for jac_jac_my_sin:
> .../casadi/core/callback_internal.cpp:122: Error calling "eval" for object jac_jac_my_sin:
> .../casadi/core/callback_internal.cpp:122: Assertion "(self_)!=0" failed:
> Callback object has been deleted") [.../casadi/core/oracle_function.cpp:223]
> CasADi - 2023-06-05 15:02:48 WARNING("Failed to calculate multipliers") [.../casadi/core/nlpsol.cpp:621]
>       solver  :   t_proc      (avg)   t_wall      (avg)    n_eval
>     nlp_grad  |  82.00us ( 82.00us)  81.75us ( 81.75us)         1
>   nlp_grad_f  | 238.00us (119.00us) 239.63us (119.82us)         2
>    nlp_jac_g  |   3.00us (  1.50us)   3.22us (  1.61us)         2
>        total  | 745.00us (745.00us) 742.73us (742.73us)         1
> 

       
And I get the same error if I do not pass "ipopt.hessian_approximation" : "limited-memory" to Ipopt and I use "enable_fd": True in the construct of JacFun. @jgillis do you know what is going on here?

**Comment by jgillis** [comment]
Looks like one of your Callback instances goes out of scope and is garbage collected. Make sure you keep a Python reference alive

**Comment by gianluigigrandesso** [comment]
Thanks @jgillis, everything is working now!
