### ISSUE TITLE
GCC 4.7.2 compilation errors

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1998]
I'm getting the following errors with MinGW (gcc 4.7.2?) after recent refactoring. It looks like a GCC bug but there might be a simple workaround.

**Comment by jaeandersson** [comment]
Working revision: 58e8ee
To do: git bisect

**Comment by jaeandersson** [comment]
Result of git bisect:

81836b5351304d727bf44d71ce6f287ca03409d3 is the first bad commit
commit 81836b5351304d727bf44d71ce6f287ca03409d3
Author: Joel Andersson <j.a.e.andersson@gmail.com>
Date:   Wed Nov 16 11:34:01 2016 -0600

    Issue #1894 Removed Function::{forward,reverse} from public API

:040000 040000 ef4dc1456de4000cb86dfeb01439519e903b9f89 4370d1d56e2896916c3a8c4621cf388fa9bc51f4 M      casadi
:040000 040000 d8b5b25c54c919278d7a29284e1a9376b5fd1f0a e23b5c5a0541a9513e1fc7fb986755b9b319e37d M      test

**Comment by jaeandersson** [comment]
Patch?

diff --git a/casadi/core/matrix_impl.hpp b/casadi/core/matrix_impl.hpp
index 16dbe52..d27fca2 100644
--- a/casadi/core/matrix_impl.hpp
+++ b/casadi/core/matrix_impl.hpp
@@ -2559,9 +2559,9 @@ namespace casadi {
 
     // Calculate directional derivatives
     if (tr) {
-      ww = reverse({ex}, {arg}, ww);
+      ww = MatType::reverse({ex}, {arg}, ww);
     } else {
-      ww = forward({ex}, {arg}, ww);
+      ww = MatType::forward({ex}, {arg}, ww);
     }
 
     // Get results

**Comment by jgillis** [comment]
Sounds moot
