### ISSUE TITLE
Compilation error in mem.h

### ISSUE THREAD

**Issue by roversch** [casadi/casadi#2319]
This fails to compile with CasADi 3.4.5: 

```
#include "casadi/mem.h"

int main(int argc, char const *argv[]) { return 0; }
```

when compiling as (with `g++-7.3.0`)

```
g++ test_casadi.cpp -I/<path_to_casadi>/casadi/include
```

with error (note that with gcc it compiles, but with warnings about incompatible pointer types)

```
/home/<user>/.local/lib/python3.6/site-packages/casadi/include/casadi/mem.h: In function ‘void casadi_decompress(const int*, int*, int*, int*, int*, const int**, const int**)’:
/home/<user>/.local/lib/python3.6/site-packages/casadi/include/casadi/mem.h:78:15: error: cannot convert ‘const long long int [2]’ to ‘const int*’ in assignment
     *colind = scalar_colind;
               ^~~~~~~~~~~~~
/home/<user>/.local/lib/python3.6/site-packages/casadi/include/casadi/mem.h: In function ‘void casadi_init_arrays(casadi_mem*)’:
/home/<user>/.local/lib/python3.6/site-packages/casadi/include/casadi/mem.h:187:58: error: cannot convert ‘const long long int*’ to ‘const int*’ for argument ‘1’ to ‘void casadi_decompress(const int*, int*, int*, int*, int*, const int**, const int**)’
                       &mem->in[i].colind, &mem->in[i].row);
                                                          ^
/home/<user>/.local/lib/python3.6/site-packages/casadi/include/casadi/mem.h:196:60: error: cannot convert ‘const long long int*’ to ‘const int*’ for argument ‘1’ to ‘void casadi_decompress(const int*, int*, int*, int*, int*, const int**, const int**)’
                       &mem->out[i].colind, &mem->out[i].row);
```

Adding a `#define casadi_int int` makes the errors go away.

**Comment by jgillis** [comment]
Thanks for reporting! I have no idea what `mem.h` is for, so it's not unittested and breaks constantly :-/

**Comment by roversch** [comment]
Thanks for the heads up. I use it for the definitions of `casadi_eval_t` and the like.

**Comment by roversch** [comment]
I just saw PR #2279 by @mkatliar . That should fix this issue.
