### ISSUE TITLE
Numpy 1.20 does not work with casadi 3.5.5-1

### ISSUE THREAD

**Issue by LouKordos** [casadi/casadi#2743]
Hi, I've been looking for a solution but have not been able to find anything, and this is the only place I can think of for asking about a possible bug of casadi.

Here is the error traceback:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/lib/python3.9/site-packages/casadi/casadi.py in __array__(self, *args, **kwargs)
   5566           try:
-> 5567             return self.full()
   5568           except:

AttributeError: 'SX' object has no attribute 'full'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-12-bae8803a4062> in <module>
    344         #ubg += [0] * 2 * 3
    345 
--> 346     r_left_skew_symmetric_symbolic = np.array([[0, -r_z_left_symbolic, r_y_left_symbolic],
    347                                       [r_z_left_symbolic, 0, -r_x_left_symbolic],
    348                                       [-r_y_left_symbolic, r_x_left_symbolic, 0]])

/usr/lib/python3.9/site-packages/casadi/casadi.py in __array__(self, *args, **kwargs)
   5567             return self.full()
   5568           except:
-> 5569             raise Exception("Implicit conversion of symbolic CasADi type to numeric matrix not supported.\n"
   5570                        + "This may occur when you pass a CasADi object to a numpy function.\n"
   5571                        + "Use an equivalent CasADi function instead of that numpy function.")

Exception: Implicit conversion of symbolic CasADi type to numeric matrix not supported.
This may occur when you pass a CasADi object to a numpy function.
Use an equivalent CasADi function instead of that numpy function.
```

I am constructing constraints for different states in my NLP and am using `np.array` for a compact way of setting an SX matrix. I have not found any other way of using a similar way of writing it with casadi so I used this, and it worked fine until a recent update, most likely going from numpy 1.19 to 1.20. It works fine in an ubuntu 20.04 VM with numpy 1.17.4.

I was a bit surprised that the error message explicitly says I shouldn't use numpy, as it worked perfectly in a previous release.

Thanks in advance, please tell me if I need to provide anything else!

**Comment by jgillis** [comment]
Thank you!
I was not aware of issues

**Comment by LouKordos** [comment]
No problem :-) So I take it casadi should generally work the way I use it in the example? I.e.:

```
H_body_world = SX.sym('H_body_world', 4, 4)

H_body_world = np.array([[cos(state[2, 0])*cos(state[1, 0]), -sin(state[2, 0])*cos(state[1, 0]), sin(state[1, 0]), state[3, 0]],
                         [sin(state[0, 0])*sin(state[1, 0])*cos(state[2, 0]) + sin(state[2, 0])*cos(state[0, 0]), -sin(state[0, 0])*sin(state[2, 0])*sin(state[1, 0]) + cos(state[0, 0])*cos(state[2, 0]), -sin(state[0, 0])*cos(state[1, 0]), state[4, 0]], 
                         [sin(state[0, 0])*sin(state[2, 0]) - sin(state[1, 0])*cos(state[0, 0])*cos(state[2, 0]), sin(state[0, 0])*cos(state[2, 0]) + sin(state[2, 0])*sin(state[1, 0])*cos(state[0, 0]), cos(state[0, 0])*cos(state[1, 0]), state[5, 0]],
                         [0, 0, 0, 1]])
```
where `state` is also `SX`.

**Comment by scchow** [comment]
I can confirm that this is an issue.

I have one environment running numpy 1.19.2 that works fine.
However porting the code into a new environment running 1.20.2 gives the following exception:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda3/envs/clrrt/lib/python3.9/site-packages/casadi/casadi.py in __array__(self, *args, **kwargs)
   5566           try:
-> 5567             return self.full()
   5568           except:

AttributeError: 'SX' object has no attribute 'full'

During handling of the above exception, another exception occurred:
... 
< extraneous backtrace snipped> 
...

--> 188         skews = np.array(
    189             [[     0,     0,     0,     0, dx[2], dx[1]],
    190              [     0,     0,     0, dx[2],     0, dx[0]],

~/miniconda3/envs/clrrt/lib/python3.9/site-packages/casadi/casadi.py in __array__(self, *args, **kwargs)
   5567             return self.full()
   5568           except:
-> 5569             raise Exception("Implicit conversion of symbolic CasADi type to numeric matrix not supported.\n"
   5570                        + "This may occur when you pass a CasADi object to a numpy function.\n"
   5571                        + "Use an equivalent CasADi function instead of that numpy function.")

Exception: Implicit conversion of symbolic CasADi type to numeric matrix not supported.
This may occur when you pass a CasADi object to a numpy function.
Use an equivalent CasADi function instead of that numpy function.
```

pointing to the line where I put a Casadi.SX object into a numpy array. 

Was this an intended change to deprecate support between Casadi variables and Numpy arrays?

**Comment by spenrich** [comment]
I can also confirm this is an issue with numpy 1.21.2. It seems like it even pops up when running `python alltests.py` (see partial output below) after building and installing from source (via these instructions: https://github.com/casadi/casadi/wiki/InstallationLinux).

![image](https://user-images.githubusercontent.com/20713988/146238552-d592432a-39c6-4ce0-b97c-b2611fa41b60.png)

**Comment by jgillis** [comment]
Probable culprit: https://numpy.org/doc/stable/release/1.20.0-notes.html#arraylike-objects-which-do-not-define-len-and-getitem

**Comment by cknoll** [comment]
Currently version 3.5.5, which is affected by this issue, seems to be the latest version available via pip. Thus for me it the easiest way to solve this issue is the following monkeypatch (which has to be applied before any other casadi-related code):
```python
import casadi

# this is a workaround for issue #2743:
# it shoud be obsolete for casadi version >= 3.6

# source of this function https://github.com/jcotem/casadi/commit/08c5f39156140817200e207b7696f59223458ce0#diff-3dc05d8ab5896084984b420dd6495df43d2e19e5f7e64693cd516bc2da0dfbf7
# referenced here https://github.com/casadi/casadi/issues/2743

def __array__(self,*args,**kwargs):
    import numpy as n
    if len(args) > 1 and isinstance(args[1],tuple) and isinstance(args[1][0],n.ufunc) and isinstance(args[1][0],n.ufunc) and len(args[1])>1 and args[1][0].nin==len(args[1][1]):
      if len(args[1][1])==3:
        raise Exception("Error with %s. Looks like you are using an assignment operator, such as 'a+=b'. This is not supported when 'a' is a numpy type, and cannot be supported without changing numpy itself. Either upgrade a to a CasADi type first, or use 'a = a + b'. " % args[1][0].__name__)
      return n.array([n.nan])
    else:
      if hasattr(self,'__array_custom__'):
        return self.__array_custom__(*args,**kwargs)
      else:
        try:
          return self.full()
        except:
          if self.is_scalar(True):
            # Needed for #2743
            E=n.empty((),dtype=object)
            E[()] = self
            return E
          else:
            raise Exception("!!Implicit conversion of symbolic CasADi type to numeric matrix not supported.\n"
                      + "This may occur when you pass a CasADi object to a numpy function.\n"
                      + "Use an equivalent CasADi function instead of that numpy function.")


# monkey-patch the casadi datatype

casadi.casadi.SX.__array__ = __array__
```
