### ISSUE TITLE
Source does not build on Mac OSX (2.4.2)

### ISSUE THREAD

**Issue by adomahidi** [casadi/casadi#1659]
When trying to build from source (after CMaking) it seems something goes wrong in the build process:

```

casadi/core/function/integrator.cpp:45:13: error: no matching member function for call to 'erase'
      opts2.erase(it);
      ~~~~~~^~~~~
```

That's strange since I checked out version 2.4.2 ... any ideas?

**Comment by jaeandersson** [comment]
That's a weird error. What compiler are you using? In principle, you could also check out the develop branch, since the function in question has been removed there...
